services:

  certbot:
    container_name: certbot
    image: certbot/certbot
    labels:
      io.portainer.accesscontrol.teams: gpes
    ports:
      - '80:80'
      - '443:443'
    networks:
      netlab01:
        ipv4_address: ${CERTBOT_HOST}
    volumes:
      - certificates:/etc/letsencrypt:rw
      - $PWD/var/log:/var/log:rw
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: 
      - 'renew'
      - '--force-renewal'
      - '--no-random-sleep-on-renew'
      - '--dry-run'

volumes:
  certificates:
    name: certificates
    external: true

networks:
  netlab01:
    external: true
