#!/usr/bin/env bash
set -euo pipefail


if [[ $# -ne 1 ]]; then

    echo "Informe [ gpes ]"

    exit 1

elif [ "$1" == "gpes" ]; then


    # Servidores de homologação
    export LAB_DOMAIN=gpes.ita.br
    
else

    echo "Argumento $1 incorreto. Use [ gpes ]"

    exit 1

fi

source ./config

cd ../certbot
echo '* Letsencrypt certbot *'

echo 'Certificar que apache está parado'
docker stop httpd || true

if [ "$1" == "gpes" ]; then
    export CERT_DOMAINS=$LAB_DOMAIN
fi
echo 'Registrando '${CERT_DOMAINS}

# Usando docker
# Verificar em stack.yml se está configurado para criação ou renovação
docker compose -f renew.yaml -f ../common/volumes.$1.yaml up --detach
docker compose -f register.yaml -f ../common/volumes.$1.yaml up --detach
echo "$(tput setaf 1)Aguarde a finalização da execução$(tput sgr0)"
docker logs certbot --follow

# Usando letsencrypt
# sudo certbot certonly --standalone --agree-tos -m gomesjm@ita.br -n -d ${CERT_DOMAINS}
# sudo certbot renew --force-renewal

echo "$(tput setaf 1)Re-inicar apache com script setup$(tput sgr0)"
